### ISSUE TITLE
Gir creates broken links to objects

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gir#1109]
I you currently look at the gtk4-rs Button docs, you will see quite a few of broken references.
For example:
"Button-like widgets like [classGtk.ToggleButton], [classGtk.MenuButton], [classGtk.VolumeButton], [classGtk.LockButton], [classGtk.ColorButton] or [classGtk.FontButton] use style classes such as .toggle, .popup, .scale, .lock, .color on the button node to differentiate themselves from a plain GtkButton."

https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.Button.html

~According to @bilelmoussaoui this happens because the ExtManual traits are only in prelude.~ (we were talking about different things)

**Comment by MarijnS95** [comment]
Gir doesn't  understand this pattern in the [documentation](https://raw.githubusercontent.com/gtk-rs/gir-files/6088bb634a406402f308f01d2f33067951d5095b/Gtk-4.0.gir):

```
Button-like widgets like [class@Gtk.ToggleButton], [class@Gtk.MenuButton],
[class@Gtk.VolumeButton], [class@Gtk.LockButton], [class@Gtk.ColorButton]
or [class@Gtk.FontButton] use style classes such as .toggle, .popup, .scale,
.lock, .color on the button node to differentiate themselves from a plain
`GtkButton`.
```

It triggers on the `@Gtk.ToggleButton` part but doesn't generate a link for it because no symbol with that name is found, afaik, and runs into:

https://github.com/gtk-rs/gir/blob/a972bd6d8d02cd44992811bd0a73b1da01c3a261/src/codegen/doc/format.rs#L121-L123

**Comment by bilelmoussaoui** [comment]
The same way there's also [method@Gtk.Window.set_default_size], [enum@Gtk.SomeEnum], [vfunc@Gtk.Window.some_vfunc] & [signal@Gtk.Widget::some_signal] 

The method/enum/class should be pretty easy to handle I guess, at least in general. The signal/vfunc are not at all :)

**Comment by bilelmoussaoui** [comment]
There seems to be a `property` thing as well
