### ISSUE TITLE
docs: Links are shown with crate:: prefix

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gir#1140]
While the `crate::` link works fine, it should be hidden in the output. Something like

```
[`Widget`](struct@gio::Widget)
```

That's also important because it would fix confusing output like `crate::glib` in gtk.

**Comment by sophie-h** [comment]
cc @MarijnS95

**Comment by MarijnS95** [comment]
#1128

**Comment by sophie-h** [comment]
I see. That sounds kind of hopeless.

Example for a lot of noise

 https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.ApplicationWindow.html#implements

Example for `crate::gio`

https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.GtkWindowExt.html#tymethod.set_application

**Comment by MarijnS95** [comment]
It's a tricky one. I mentioned on IRC I was already coming back from this decision because `crate::` really does look ugly. See for example the GStreamer struct/enum overview page: https://marijns95.pages.freedesktop.org/gstreamer-rs/gstreamer/#structs. OTOH this is the only way (that I know of) to make intradoc links not clickable if they don't point to anything sensible. `[]()` only detects the intradoc pattern, but leaves it to browsers to figure out if it wasn't pointing to a Rust object :/

Maybe `rustdoc` needs to solve that one way or another, or `gir` needs significant effort to check whether a link would be valid given the info it was.

**Comment by bilelmoussaoui** [comment]
one counter argument against using `crate::` everywhere https://gtk-rs.org/gtk4-rs/stable/0.1/docs/gdk4/struct.Rectangle.html#returns

**Comment by MarijnS95** [comment]
@bilelmoussaoui But why is https://gtk-rs.org/gtk4-rs/stable/0.1/docs/gdk4/struct.Rectangle.html#returns-1 not affected?

**Comment by MarijnS95** [comment]
Relevant change for prelude constants: 52a79988204b4a39e10b9ec22729e7bc9904fcef

**Comment by MarijnS95** [comment]
The GTK doc is probably using `#true` here instead of `%true`?

**Comment by MarijnS95** [comment]
@bilelmoussaoui If we were to "fix" this to hide `crate::` again the broken link would still be turned into ``[`true`](crate::true)`` unless the source doc is fixed to use `%`.

**Comment by bilelmoussaoui** [comment]
I wonder whether we should go with Self for a type's methods/constructors instead of the type's name?

**Comment by MarijnS95** [comment]
I'd say neither: at least that's what we did previously and it looks concise and clean. Afaik there are few enough free functions that a function name without type name implies it is a function on the current type - and it's a link anyway, so it doesn't really matter at the end of the day.

However, for mental sanity and short-ness I've used Self:: in the link-part (that you don't see).

**Comment by MarijnS95** [comment]
Having worked on this some more on Bilel's branch, it is a really tricky subject. We have two parts:

1. The visual name/item-path in the documentation;
2. The actual item path in the (Rust) documentation (used by rustdoc to generate the right page link).

This issue mainly concerns the first bulletpoint, so I'll be short on the second. To match earlier behaviour, to shorten/simplify the documentation, and for absolute paranoia, I prefer to use `Self::` where possible. This is easy for all types, except for objects. Objects consist of three distinct types:

- `impl TheObject`;
- `trait TheObjectExt`;
- `trait TheObjectExtManual`.

In order to use `Self::` here, not only do we need to check if the referenced item sits on the same type, we need to know (deep down in the documentation formatter, https://github.com/bilelmoussaoui/gir/pull/6) in which of the three contexts/types the link is generated.
In the end objects might be a necessary case that never use `Self::`, in favour of keeping the code simpler.

However, the same has to be discussed for bullet point 1., visual naming in the rendered docs:

- `Variant` and `some_func()`;
- `Self::Variant` and `Self::some_func()`;
- `ThisType::Variant` and `ThisType::some_func()`.

I personally prefer the first. It is short and concise, and it's a clickable link anyway in case the reader isn't sure where the item actually lives. Functions are usually short enough that the reader isn't left wondering whether a free function is referenced instead of a method/associated function. The second is verbose in a weird way, just like `crate::` is. The third is also quite verbose, and leaves the reader wondering for a split-second: "I'm on the docs page for `ThisType` already, right? So it's available right here.".

That last bullet point brings us back to the three distinct types on objects: it IMO makes a lot of sense to prefix the appropriate type when cross-referencing. A reader on the `struct/impl TheObject` page should be made aware that a function, while technically on the same "gir type", actually lives under the `Ext` or `ExtManual` trait as an overridable function. The same applies when linking back from virtual methods to methods/associated functions.
(The full type is already displayed currently, and the question here is whether we should omit that [and use `Self::` under the hood] as simplification, at the cost of more complex `gir` code).

**Comment by bilelmoussaoui** [comment]
This can be closed now as well
