### ISSUE TITLE
codegen: assert that TRUE is returned XOR the GError is set

### ISSUE THREAD

**Issue by lucab** [gtk-rs/gir#1279]
From the [glib guide](https://docs.gtk.org/glib/error-reporting.html):

> If FALSE is returned, the error must be set to a non-NULL value.
> One exception to this is that in situations that are already considered to be undefined behaviour (such as when a g_return_val_if_fail() check fails), the error need not be set.
> Instead of checking separately whether the error is set, callers should ensure that they do not provoke undefined behaviour, then assume that the error will be set on failure.

Right now `gir` generates function wrappers like these:
```
let mut error = ptr::null_mut();
let _ = ffi::wrapped_fn(..., &mut error);
if error.is_null() { Ok(...) } else { Err(from_glib_full(error)) }
```

So the auto-generated Rust logic can totally miss those "undefined behaviour" cases where `FALSE` is returned but no GError is set (hopefully it never gets into those cases, but ...).
Worse, those cases will end up in the `Ok(...)` happy path from the point of view of the consumer.
The status quo is at least sketchy if not actually unsound; it would be great to have an auto-generated `assert!()` to make sure the `Ok(...)` result in not actually coming as the result of stepping into glib undefined behaviour.

**Comment by sdroege** [comment]
Yes, go for it :)

**Comment by cgwalters** [comment]
We had a big chat about this on Matrix (and also some between luca and me on a private chat system) and I'm just writing down my 2¢ which is:

In modern times, `g_return_if_fail()` is almost always a bad idea and should be replaced with one of:

- `g_assert()`
- Returning a GError
- Rust

In particular for ostree because the whole thing is transactional/restartable/stateless, we can always cleanly abort.  And doing so is better than potentially introducing memory corruption or undefined behavior.

**Comment by lucab** [comment]
Yes for context I spot this on `ostree-rs`, where the underlying C library accumulated ~200 of those `g_return_val_if_fail (..., FALSE)` over time. And I'm guilty of adding several of them quite recently as I was unaware of this potential undefined corner case.
We can/should clean up libostree, but I think this pitfall does not only apply to this library and me.
