### ISSUE TITLE
gir generate signals requiring undefined macro callback_guard!()

### ISSUE THREAD

**Issue by hfiguiere** [gtk-rs/gir#271]
gir generate signals requiring undefined macro callback_guard!(). Undefined if gir is used outside of gtk-rs.

Example: gudev-rs.

https://github.com/hfiguiere/gudev-rs/blob/36a694b0eef549375f09afd709910fc3882f8dc0/src/auto/client.rs#L70

Maybe it is just a matter of adding it to the generated code.

**Comment by hfiguiere** [comment]
Updated the link to the code to use the actual revision in case I find a work around. Currently defining the macro as no-op...

**Comment by gkoz** [comment]
We've been copying this macro around so far because the code is quite short. Might be a good idea to export it from the `glib` crate.

**Comment by gkoz** [comment]
Well, I forgot that in non-thread-safe crates `callback_guard!` also calls `assert_initialized_main_thread!` like this:

```rust

macro_rules! callback_guard {
    () => (
        let _guard = ::glib::CallbackGuard::new();
        if cfg!(debug_assertions) {
            assert_initialized_main_thread!();
        }
    )
}
```

If we move the macro to `glib`, the generator needs to start emitting additional

```
if cfg!(debug_assertions) {
    assert_initialized_main_thread!();
}
```

in trampolines.

**Comment by sdroege** [comment]
So unless we drop the assert_initialized_main_thread!() here, just exposing the macro from glib does not solve anything. So either:

1) Rename the macro to glib_panic_guard!() and just do that in there, and export it from glib-rs to be used by other crates
2) Require crates to define their own macro in lib.rs that does whatever they want to do
3) Add a configuration for the "ffi guard macro", ffi_guard_macro="some_macro_name", which when unspecified just uses the one from glib 1) and otherwise uses that one.

I'm personally going with 2) for now, but 3) is probably the nicest solution as it allows crates to add custom code in there too. @GuillaumeGomez what do you think?

**Comment by GuillaumeGomez** [comment]
I think we should do 1), whatever we choose to do next. And I'd choose 2) instead of 3) to keep things easy.

So if possible, let's do 1) and 2).

**Comment by sdroege** [comment]
But for 2) after 1), how would we let the code generator know what to insert as custom code for this very crate?
