### ISSUE TITLE
Add option to use return value in result

### ISSUE THREAD

**Issue by bvinc** [gtk-rs/gir#580]
Glib has a few functions that return a significant `gboolean` value.  For example:

`g_key_file_get_boolean` is being generated as:
```rust
pub fn get_boolean(&self, group_name: &str, key: &str) -> Result<(), Error> {
```

`g_key_file_has_key`
```rust
pub fn has_key(&self, group_name: &str, key: &str) -> Result<(), Error> {
```

These should obviously be returning `Result<bool, Error>`.

Do you think it's worth it to add a configuration option to gir to signify that the return value should be used as a result?

**Comment by tmiasko** [comment]
Sounds reasonable, especially if there are others like that. Otherwise manual
implementation might require less maintenance than having it in gir generator.

There was a proposal to add another version g_key_file_has_key to GLib with
with usual GError semantics and separate boolean output parameter, but it was
eventually scrapped, because g_key_file_get_value was consider sufficient
replacement for introspection based languages.

**Comment by sdroege** [comment]
Are there any other cases of this? If the number of cases is small, a manual implementation seems better.

**Comment by EPashkin** [comment]
Agree, it seems rare cases and better be manual

**Comment by bvinc** [comment]
I just found 3 in glib.  I guess there aren't very many.  I'll close this.

**Comment by EPashkin** [comment]
@bvinc which function is the third?

**Comment by bvinc** [comment]
`spawn_check_exit_status`

BTW, I'm making a PR for them right now.

**Comment by EPashkin** [comment]
Thanks in advance
