### ISSUE TITLE
Remove `Into` trait

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gir#722]
It leads to very annoying situations like:

```Rust
let scroll = gtk::ScrolledWindow::new(None::<&gtk::Adjustment>, None::<&gtk::Adjustment>);
```

**Comment by sdroege** [comment]
I refer you to https://github.com/gtk-rs/gir/issues/713 where I said exactly that a while ago but you didn't believe me :) That's why we now have `gtk::NONE_ADJUSTMENT` as a workaround.

**Comment by GuillaumeGomez** [comment]
I wasn't sure you'd take it well if I added "just like @sdroege said a while ago". :-.

**Comment by sdroege** [comment]
After some discussion on IRC, dropping the `Into<Option<_>>` bound is not actually solving our problem here. `foo<T: IsA<Thing>>(v: Option<&T>)` has exactly the same problem. The problem is having an `Option<_>` that is generic over any trait.

RFC 0213 (defaulted-type-params) would kind of solve it, but it does not apply to functions and is not stable. Reason why it does not apply to functions is explained here https://github.com/rust-lang/rust/issues/36887#issuecomment-296460292

So right now we have 4 possible solutions
1) keep it and document it,
2) drop the IsA and require users to upcast,
3) make IsA object-safe and do Option<&dyn IsA<T>>,
4) type parameter defaults also for functions

My vote would currently be for 1). 2) only moves the problem around and requires the user to do something else that will be equally confusing. 3) I tried for a few days and failed. And 4) requires language changes so is not going to happen anytime soon.

If someone comes up with a solution for 3) then I'd vote for that, but I don't see that happen anytime soon.

**Comment by EPashkin** [comment]
IMHO we should go to 1,
if we want remove it, then instead complete removal like in #724,
we better remove it only for non-final objects and maybe for function too (if there any),
in other cases `Into` works fine.
