### ISSUE TITLE
Change order for `use`s

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gir#738]
rustfmt places uppercases names later,
so calling it on generated code produce order change:
```diff
-use ChecksumType;
 use sys;
 use translate::*;
+use ChecksumType;
```

**Comment by sdroege** [comment]
Yes it first puts modules and then types, which makes sense :)

Why do we care about this though? The autogenerated code from `gir` is not in the format of `rustfmt` anyway, which is why I have [`#[rustfmt::skip]`](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/631eee13da3322bb1d6d254c09e9e8a8941f093e/gstreamer/src/lib.rs#L67) in `lib.rs` for the `auto` module currently.

Is the goal to make the `gir` output be the same as what `rustfmt` would generate? I'd very much like that, but maybe it would be simpler to run `rustfmt` after code generation for that until https://github.com/gtk-rs/gir/issues/661 is implemented?

**Comment by GuillaumeGomez** [comment]
It just seems alpha sorted to me. We can do that too. :)

**Comment by bilelmoussaoui** [comment]
This shouldn't be an issue now that gir produces 2018 edition code
