### ISSUE TITLE
`glib::Error` gets `use`d as `use Error` instead of `use glib::Error` when in the `manual` array

### ISSUE THREAD

**Issue by Ekleog** [gtk-rs/gir#862]
Generated code looks like https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/master/gstreamer-editing-services/src/auto/asset.rs#L24 ; with `GLib.Error` in the `manual` array of the `Gir.toml`.

This can be worked around with `use glib::Error;` at the root of the crate (as is currently done by most if not all gtk-rs crates), but without this it'd fail to compile.

I think the `use` statement should be `use glib::Error` directly, to avoid this issue :)

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by sdroege** [comment]
Maybe we can also do something so that not every crate has to re-export parts of the glib crate? See e.g. https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/blob/master/gstreamer-editing-services/src/lib.rs#L30-32

Those should all not be necessary but instead we should just properly import things ourself or address them by path...

@GuillaumeGomez @EPashkin ?

**Comment by EPashkin** [comment]
`BoolError` seems done already, `Error` too
others seems imported with "glib:`

**Comment by EPashkin** [comment]
@sdroege at minimum gtk is builds fine without it after fixing only manual code

**Comment by EPashkin** [comment]
.. but after this examples fails, because it use `gtk::Type`.

**Comment by sdroege** [comment]
Great, let's remove it everywhere then for the next release. It's just confusing :)

**Comment by sdroege** [comment]
(added it to the release tracker)
