### ISSUE TITLE
Gir tutorial: Add section for 'cannot find macro'

### ISSUE THREAD

**Issue by grelltrier** [gtk-rs/gir#957]
I followed the [tutorial](https://gtk-rs.org/docs-src/tutorial/gir_tutorial) to create a Rust wrapper for gtk-layer-shell and it mostly worked fine but I got errors saying:

cannot find macro `assert_initialized_main_thread` in this scope
cannot find macro `skip_assert_initialized` in this scope

After searching on Github i saw that people just add those macros manually.
Maybe other will have the same error. It could be helpful to add this to the tutorial. One possibility I thought of was to put it under "Generation errors". The text could say something like:

**Cannot find macro**
If gir generation fails because it can't find one of the listed macros, it means you’ll have to implement them yourself. Don't worry, its very easy. Depending on which macro is missing, you can add the following to your lib.rs file:

```
/// Asserts that this is the main thread and either `gdk::init` or `gtk::init` has been called.
macro_rules! assert_initialized_main_thread {
    () => {
        if !::gtk::is_initialized_main_thread() {
            if ::gtk::is_initialized() {
                panic!("GTK may only be used from the main thread.");
            } else {
                panic!("GTK has not been initialized. Call `gtk::init` first.");
            }
        }
    };
}

/// No-op.
macro_rules! skip_assert_initialized {
    () => {};
}
```

I don't know if this list is complete.

**Comment by sdroege** [comment]
That should definitely be added, do you want to provide a PR for that?

One complication here is that the `assert_initialized_main_thread` macro depends on the exact library. If it's GTK-based then what you wrote is likely correct, unless the library has its own initialization function (which would need to be handled in addition to GTK here). For non-GTK-based libraries this macro would do nothing if there's no library initialization function, and otherwise it handles that function.

**Comment by grelltrier** [comment]
Here is the [PR](https://github.com/gtk-rs/gtk-rs.github.io/pull/171)
I just used what I wrote above and appended your addition
